In [49]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.1


# importing data set

In [50]:
mnist = tf.keras.datasets.mnist
data = mnist.load_data()
(x_train, y_train), (x_test, y_test) = data

In [51]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [52]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ -43.642483,  102.55974 ,   39.373856,  -84.460556,  100.06486 ,
         -73.57625 ,  114.87777 ,  119.803795, -103.990685, -164.92456 ]],
      dtype=float32)

In [53]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 3.2200440e-08, 1.1656861e-35, 0.0000000e+00,
        2.6567388e-09, 0.0000000e+00, 7.2030229e-03, 9.9279696e-01,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [54]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

193.38727

In [55]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [56]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 959us/step - accuracy: 0.7158 - loss: 8.4324
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.8293 - loss: 0.6461
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 858us/step - accuracy: 0.8689 - loss: 0.5119
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 819us/step - accuracy: 0.8835 - loss: 0.4343
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 823us/step - accuracy: 0.8950 - loss: 0.3961
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.9029 - loss: 0.3696
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.9075 - loss: 0.3515
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 830us/step - accuracy: 0.9106 - loss: 0.3423
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.9197 - loss: 0.3113
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.9178 - loss: 0.3159


In [57]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - 421us/step - accuracy: 0.9444 - loss: 0.2924


[0.29237815737724304, 0.9444000124931335]

In [58]:
probabilty_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probabilty_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 4.1912143e-16, 6.2128596e-09, 1.2920277e-10,
        4.5236622e-25, 4.7830538e-14, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 7.0518990e-22],
       [0.0000000e+00, 6.5770227e-01, 3.4229612e-01, 8.7093539e-08,
        1.9460440e-21, 9.9506568e-13, 2.0755368e-16, 1.5122425e-06,
        1.1947946e-15, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 6.7062556e-17, 3.3888531e-26,
        3.4803879e-13, 1.6127841e-16, 4.6353817e-14, 3.8066890e-11,
        2.4853276e-22, 1.3955293e-32],
       [9.9996513e-01, 0.0000000e+00, 2.5363181e-07, 1.9360359e-14,
        1.6465670e-12, 2.4745817e-09, 1.9575310e-07, 3.4477875e-05,
        1.4548130e-15, 3.5723837e-11],
       [3.8817973e-11, 2.0599464e-09, 1.7782769e-08, 7.8524698e-09,
        9.9999964e-01, 1.1855547e-09, 9.3899950e-11, 2.8313030e-07,
        1.2603006e-10, 1.9667517e-08]], dtype=float32)>